# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-cron-mf
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: mf_endpoint.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role: arn:aws:iam::575834425578:role/lambda_dynamodb_logs


functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/v1/funds
          method: get
      - http:
          path: /api/v1/funds
          method: post
      - http:
          path: /api/v1/funds
          method: put
      - http:
          path: /api/v1/funds/{id}
          method: get
      - http:
          path: /api/v1/funds/update/nav
          method: get
      - http:
          path: /api/v1/funds/update/nav/{id}
          method: get

      - http:
          path: /api/v1/user/{user_id}/funds
          method: get
      - http:
          path: /api/v1/user/{user_id}/funds
          method: post
      - http:
          path: /api/v1/user/{user_id}/funds/{mf_id}
          method: get
      - http:
          path: /api/v1/user/{user_id}/funds/update
          method: get

      - http:
          path: /hello
          method: get
      - http:
          path: /hello/{name}
          method: get
      - http:
          path: /funds/{user_id}
          method: get
      - http:
          path: /funds/{user_id}/update
          method: get

  scheduler:
    handler: handler.hello
    events:
      - schedule:
          # Invoke Lambda function Run at 06:30 am (UTC):12 AM IST every Monday through Saturday
          rate: cron(30 6 * * ? *)
          enabled: true
      - schedule:
          # Invoke Lambda function Run at 23:30 pm (UTC):5 AM IST everyDay
          rate: cron(30 23 * * ? *)
          enabled: true
      - schedule:
          # Invoke Lambda function Run at 12:30 am (UTC):6 AM IST every Monday through Saturday
          rate: cron(30 0 ? * MON-SAT *)
          enabled: true
      - schedule:
          # Invoke Lambda function Run at 4:00 am (UTC):9:30 AM IST every Monday through Saturday
          rate: cron(0 4 ? * MON-SAT *)
          enabled: true
      - schedule:
          # Invoke Lambda function Run at 10:30 am (UTC):4 PM IST every Monday through Saturday
          rate: cron(30 10 * * ? *)
          enabled: true
      - schedule:
          # Invoke Lambda function testing everyDay
          rate: cron(15 4 * * ? *)
          enabled: false

