# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-cron-mf
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  iam:
    role: arn:aws:iam::575834425578:role/lambda_dynamodb_logs


functions:
  hello:
    handler: handler.hello



plugins:
  - serverless-python-requirements
